version: '3.9'

services:
  fast-api-api:
    container_name: fast-api-api
    image: fast-api-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/home/app
    depends_on:
      - fast-api-db
    env_file:
      - ./.env
    # tty: true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  fast-api-db:
    container_name: fast-api-db
    image: postgres:13-alpine
    volumes:
      - fastapirob_data:/var/lib/postgresql/data/

    ports:
      - "5435:5432"
    env_file:
      - ./.env

  fast-api-rabbit:
    container_name: fast-api-rabbit
    image: rabbitmq:3.11.10-management 
    ports:
        - 5675:5672
        - 15672:15672
    env_file:
      - ./.env

  fast-api-celery:
    container_name: fast-api-celery
    image: fast-api-celery
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/app:/home/app
    # tty: true
    command: celery -A celery_src.main_celery worker -l info

    depends_on:
      - fast-api-rabbit
      - fast-api-api

  fast-api-flower:
    container_name: fast-api-flower
    image: fast-api-flower
    build:
      context: .
      dockerfile: Dockerfile.flower
    volumes:
      - ./src/app:/home/app
    env_file:
      - ./.env
    # tty: true
    command: ["celery", "-A", "celery_src.main_celery", "flower", "--broker=amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$RABBITMQ_DEFAULT_HOST:5672//"]

    ports:
        - 5555:5555
    depends_on:
        - fast-api-rabbit

volumes:
  fastapirob_data:
