version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/home/app
    depends_on:
      - db
    # stdin_open: true
    # tty: true
    command: ["uvicorn","main:app","--host=0.0.0.0","--port=8000","--reload"]

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - fastapirob_data:/var/lib/postgresql/data/

    ports:
      - "5435:5432"
    env_file:
      - ./.env


  rabbit:
    container_name: rabbit
    image: rabbitmq:3.11.10-management 
    ports:
        - 5675:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

volumes:
  fastapirob_data: